version: '3.8'


services:
  # keshet_mcp:
  #   build: .
  #   ports:
  #     - "8001:8000"
  #   environment:
  #     - VENDOR=keshet

  # rami_levy_mcp:
  #   build: .
  #   ports:
  #     - "8002:8000"
  #   environment:
  #     - VENDOR=rami-levy

  shufersal_mcp:
    build: .
    ports:
      - "58003:8888"
    env_file:
      - .env
    environment:
      VENDOR: shufersal
      PLAYWRIGHT_WS_URL: ws://playwright-server:3000
    volumes:
      - /var/lib/groceries_mcp_data:/var/lib/groceries_mcp_data/
    depends_on:
      - playwright-server
    restart: always

  playwright-server:
    image: mcr.microsoft.com/playwright:v1.58.0-noble
    command: npx playwright run-server --port 3000 --host 0.0.0.0
    ports:
      - '0.0.0.0:3031:3000'
    environment:
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080
    restart: always

  agent:
    build: 
      context: .
      dockerfile: ./mcp_groceries_server/agent/Dockerfile
    env_file:
      - .env
    ports:
      - "58083:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: always  


  
