version: '3.8'


services:
  # keshet_mcp:
  #   build: .
  #   ports:
  #     - "8001:8000"
  #   environment:
  #     - VENDOR=keshet

  # rami_levy_mcp:
  #   build: .
  #   ports:
  #     - "8002:8000"
  #   environment:
  #     - VENDOR=rami-levy

  shufersal_mcp:
    build: .
    ports:
      - "58003:8000"
    env_file:
      - .env
    environment:
      - VENDOR=shufersal
    volumes:
      - /var/lib/groceries_mcp_data:/var/lib/groceries_mcp_data/

  agent:
    build: 
      context: .
      dockerfile: ./mcp_groceries_server/agent/Dockerfile
    env_file:
      - .env
    ports:
      - "58083:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:58083/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
      


  
